name: build

env:
  CARGO_TERM_COLOR: always

on: [push, pull_request]

jobs:
  rust:
    name: Check rust
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - nightly-2020-12-20
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
  yarn:
    name: Build yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd web install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd web build
