name: test coverage

env:
  CARGO_TERM_COLOR: always

on: [push, pull_request]

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      RUSTFLAGS: "-Zinstrument-coverage"
    steps:
      - run: "echo ref ${GITHUB_REF}, sha ${GITHUB_SHA}, repo ${GITHUB_REPOSITORY}, head ref ${GITHUB_HEAD_REF}"
      - name: Install dependencies
        run: sudo apt-get install libjack-dev
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add llvm-tools-preview
      - uses: actions-rs/install@v0.1
        with:
          crate: grcov
          version: latest
          use-tool-cache: true
      - run: cargo build
      - run: cargo test
      - run: ls -l
      - run: grcov . --binary-path ./target/debug -s . -t lcov --branch --ignore-not-existing -o lcov.info
      - run: ls -l lcov.info
      - run: "echo ref ${GITHUB_REF}, sha: ${GITHUB_SHA}, repo: ${GITHUB_REPOSITORY}, head ref: ${GITHUB_HEAD_REF}"
      - run: bash <(curl -s https://codecov.io/bash) -f lcov.info
      - uses: actions/upload-artifact@v2
        with:
          name: lcov.info
          path: lcov.info

