name: test suite

env:
  CARGO_TERM_COLOR: always

on: [push, pull_request]

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - nightly
          - nightly-2020-12-20
    steps:
      - name: Install dependencies
        run: sudo apt-get install libjack-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

